name: Continuous Integration (because stating the obvious is hilarious)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        architecture: 'x64'
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make tests
      run: make tests
    - name: test with JNI
      run: cd jni && make test
    - name: run interactive (sort of)
      run: cd jni && make testbye
    - name: run life1d example
      run: cd src && make build && ./post4 ../examples/life1d.p4
    - name: make distclean
      run: make distclean
