name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: joschi/setup-jdk@v2
      with:
        java-version: '17    # The OpenJDK version to make available on the path
        architecture: 'x64'
      run: ./configure
    - name: make
      run: make
    - name: make test
      run: make test
    - name: make distclean
      run: make distclean
