name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        architecture: 'x64'
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make test
      run: make test
    - name: make distclean
      run: make distclean
